ja:
  activerecord:
    models:
      media_item: "作品"
    attributes:
      media_item:
        title: "タイトル"
        creator: "作者・アーティスト"
        description: "説明"
  errors:
    format: "%{attribute} %{message}"
